### PR TITLE
Overwrite

### PR DESCRIPTION
**Pull request by lijuan**
This branch implement 'drop' feature for asyn/syn queries saving to mydb, if the table name already exists, drop=true will automate drop the old table and create the new table, drop=false will give error message that table name already exists.

### CODE REVIEW

**Comment by rnikutta** [comment]
Hi @lijuan thanks; I tested this, here are my observations:

- SQL query with out to mydb works
- Doing it again raises Exception, as expected
- Adding drop=True to qc.query() call works
- ADQL query with out to a new (non-existing) table to mydb does NOT work

```
q = 'select top 4 ra,dec,source_id from gaia_dr2.gaia_source'
res = qc.query(adql=q,fmt='csv',out='mydb://test_droptable2')
[...]
queryClientError: Error: u'"test_droptable2"'

```
- Consequently, ADQL query with write out to an existing mydb table also fails in the same way.

- qc.mydb_drop(<tablename>) prints 'OK' when <tablename> doesn't actually exist in mydb. It should issue a RuntimeWarning to let the user know that no action was performed because <tablename> wasn't present in the user's mydb.

**Comment by lijuan** [comment]
> * ADQL query with out to a new (non-existing) table to mydb does NOT work

This is a different issues not related to existing table name, adql/sync saving to mydb does not work even if the table name does not exist. You need to create a separate ticket to fix this issue.

qc.mydb_drop() prints 'OK' when doesn't actually exist in mydb. It should issue a RuntimeWarning to let the user know that no action was performed because wasn't present in the user's mydb.

--This is also a non-related issue, mydb_drop does not generate error message when it fails, it maybe already fixed in the output branch. If not, you need to create a separate ticket for this.

**Comment by rnikutta** [comment]
Let's strive for a wholesome approach to usability and task completeness. Testing if only the left blinker works on your car but not the right one seems a bit incomplete, right? ;-)
Please make those tickets if you prefer; I consider that I hereby reported those issues.
Thanks.

**Comment by lijuan** [comment]
I will create a ticket and fix that issue on a separate branch because it is a different issue. Let's merge and deploy this first. Otherwise we will stuck at testing forever.

**Comment by rnikutta** [comment]
Agreed, of course! Thank you

**Comment by lijuan** [comment]
Adql queries not able to save to mydb has been fixed.

**Pull request merged**
