### PR TITLE
fix qc.mydb_list() should only return table names by default, no crea…

### PR DESCRIPTION
**Pull request by lijuan**
…tion timestamps #31

### CODE REVIEW

**Review by mjfitzpatrick — APPROVED** [review]
Note no newline at end of queryClient.py.  Version bumps normally done for each new release since versions can include multiple changes -- okay for now if you're planning an immediate deployment.

**Comment by rnikutta** [comment]
Thanks for the PR and review request.

* How far are we from the desired end-state scenario that a change like this could be deployed to a test VM/env, wher it could be tested? Just looking at code how can we tell that "it will work"?

By "just looking at the code", a few comments:

* It looks as if the value of `verbose` is not tested at all, only that it's not None. Is that correct? And desired? Wouldn't it be much safer to require and explicit `if verbose is True:` ?
* I don't like at all that a function needed to be written to *remove* the `create:foobar` string. Where is the comment stored originally? Much cleaner would be to only *add* it when requested. Is that technically not possible for some reason?
* I suspect this is a larger discussion to be had, but a simplistic check like this to "verify" if a token is a token seems like a bad idea / asking for trouble:
```
if optval is not None and len(optval.split('.')) >= 4:
    # optval looks like a token
    return self._mydb_list (token=def_token(optval), table=table, index=index, **kw)
```
(unless `def_token` is a proper token validation method?)

**Comment by lijuan** [comment]
I tested it myself and I believe other developers know how to test it too.

I didn't create verbose parameter, I cam simply follow the existing pattern for verbose in the queryClient code. Creating test cases for parameters is a separate and bigger issue, need to create a different ticket or epic for that.

The reason we need to remove it from the query result is because the create time was added to the database when the table was created, there is no way we can get the query results without the create time.

The token is not added for this ticket, it is a different issue, if you want to change it, please create a ticket and assign it to Mike, I don't understand about the token part either.

**Comment by rnikutta** [comment]
Thank you for the clarifications. The `if verbose is True:` fix seems trivial to do, no? (here, in this PR I mean). The other stuff is probably for another day.

**Comment by mjfitzpatrick** [comment]
The "token part" is the backwards compatibility and multi-signature
interface, i.e. 'token' used to be a required first argument, now it's an
optional argument, but the code needs to know how to interpret the
arguments.  A four part token string is unlikely to be confused with a
table name.   The def_token() gets the default token (either anonymous or
from your dl.conf).

**Comment by rnikutta** [comment]
Thanks also for the clarification re tokens. What does `def_token(optval)` return then, if `optval` is a valid user token? What does it return if `optval` is *not* a valid token? Where does token validation happen?

**Comment by mjfitzpatrick** [comment]
See datalab/dl/Util.py

**Comment by lijuan** [comment]
> Thank you for the clarifications. The `if verbose is True:` fix seems trivial to do, no? (here, in this PR I mean). The other stuff is probably for another day.

verbose is a boolean value, and you want me to change 'if verbose' to 'if verbose is True'??

**Comment by rnikutta** [comment]
My comment was that is is boolean by assumption only. It is not checked to be boolean. That is, `if verbose` would return `True` for ANY value (string, number, class, ...), except for `None'.

**Comment by rnikutta** [comment]
Thanks, looks good.
Only thing missing is from Mike's comment about the missing newline in the last line?

**Pull request merged**
